# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: right_arm_zero

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    - left_palm_finger_1_joint
    - left_finger_1_joint_1
    - left_finger_1_joint_2
    - left_finger_1_joint_3
    - left_palm_finger_2_joint
    - left_finger_2_joint_1
    - left_finger_2_joint_2
    - left_finger_2_joint_3
    - left_finger_middle_joint_1
    - left_finger_middle_joint_2
    - left_finger_middle_joint_3
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
    - right_palm_finger_1_joint
    - right_finger_1_joint_1
    - right_finger_1_joint_2
    - right_finger_1_joint_3
    - right_palm_finger_2_joint
    - right_finger_2_joint_1
    - right_finger_2_joint_2
    - right_finger_2_joint_3
    - right_finger_middle_joint_1
    - right_finger_middle_joint_2
    - right_finger_middle_joint_3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: "right_arm/scaled_pos_joint_traj_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: "left_arm/scaled_pos_joint_traj_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
