controller_list:
  - name: left_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: right_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: left_gripper_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_palm_finger_1_joint
      - left_finger_1_joint_1
      - left_finger_1_joint_2
      - left_finger_1_joint_3
      - left_palm_finger_2_joint
      - left_finger_2_joint_1
      - left_finger_2_joint_2
      - left_finger_2_joint_3
      - left_finger_middle_joint_1
      - left_finger_middle_joint_2
      - left_finger_middle_joint_3
  - name: right_gripper_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_palm_finger_1_joint
      - right_finger_1_joint_1
      - right_finger_1_joint_2
      - right_finger_1_joint_3
      - right_palm_finger_2_joint
      - right_finger_2_joint_1
      - right_finger_2_joint_2
      - right_finger_2_joint_3
      - right_finger_middle_joint_1
      - right_finger_middle_joint_2
      - right_finger_middle_joint_3