controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_left_gripper_controller
    type: $(arg execution_type)
    joints:
      - left_palm_finger_1_joint
      - left_finger_1_joint_1
      - left_finger_1_joint_2
      - left_finger_1_joint_3
      - left_palm_finger_2_joint
      - left_finger_2_joint_1
      - left_finger_2_joint_2
      - left_finger_2_joint_3
      - left_finger_middle_joint_1
      - left_finger_middle_joint_2
      - left_finger_middle_joint_3
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_right_gripper_controller
    type: $(arg execution_type)
    joints:
      - right_palm_finger_1_joint
      - right_finger_1_joint_1
      - right_finger_1_joint_2
      - right_finger_1_joint_3
      - right_palm_finger_2_joint
      - right_finger_2_joint_1
      - right_finger_2_joint_2
      - right_finger_2_joint_3
      - right_finger_middle_joint_1
      - right_finger_middle_joint_2
      - right_finger_middle_joint_3
initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_arm_zero
  - group: left_gripper
    pose: left_gripper_init
  - group: right_arm
    pose: right_arm_zero
  - group: right_gripper
    pose: right_gripper_init